ALTER TABLE dbo.wwwUser ADD
	ID int NOT NULL IDENTITY (1, 1)
ALTER TABLE dbo.wwwUser
	DROP CONSTRAINT PK_wwwUser
ALTER TABLE dbo.wwwUser ADD CONSTRAINT
	PK_wwwUser PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX IX_wwwUser ON dbo.wwwUser
	(
	aUser
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	
	